on: push
name: CI
jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, small]
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==$(head -n 1 .poetry-version)

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --only main,dev --no-interaction --no-ansi --no-cache

      - name: Lint
        run: poetry run ruff --unsafe-fixes --preview --fix .

  type_checking:
    name: Static type checking
    runs-on: [self-hosted, small]
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==$(head -n 1 .poetry-version)

      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --only main,dev --no-interaction --no-ansi --no-cache
      - name: Mypy
        run: poetry run mypy .
